# Generated by Django 5.0 on 2025-12-23 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("random_forest", "Random Forest"),
                            ("gradient_boosting", "Gradient Boosting"),
                            ("xgboost", "XGBoost"),
                            ("lightgbm", "LightGBM"),
                            ("logistic_regression", "Logistic Regression"),
                            ("svm", "Support Vector Machine"),
                            ("neural_network", "Neural Network"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("classification", "Classification"),
                            ("regression", "Regression"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_file", models.FileField(upload_to="models/saved_models/")),
                ("feature_names", models.JSONField(blank=True, null=True)),
                (
                    "target_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hyperparameters", models.JSONField(blank=True, null=True)),
                ("train_accuracy", models.FloatField(blank=True, null=True)),
                ("test_accuracy", models.FloatField(blank=True, null=True)),
                ("train_metrics", models.JSONField(blank=True, null=True)),
                ("test_metrics", models.JSONField(blank=True, null=True)),
                ("is_trained", models.BooleanField(default=False)),
                ("is_pretrained", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("train_test_split", models.FloatField(default=0.8)),
                ("random_state", models.IntegerField(default=42)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("current_step", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("training_log", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="models.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
