# Generated by Django 5.0 on 2026-04-19 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
        ("datasets", "0003_alter_datasetcolumn_data_type"),
        ("models", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="analysis_name",
            field=models.CharField(default="Untitled Analysis", max_length=255),
        ),
        migrations.AddField(
            model_name="analysis",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="feature_list",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="analysis",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="models.mlmodel",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="model_type",
            field=models.CharField(default="unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="analysis",
            name="num_features",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AddField(
            model_name="analysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="frozen_features",
            field=models.JSONField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name="analysis",
            unique_together={("user", "dataset", "analysis_name")},
        ),
    ]
