# Generated by Django 5.0 on 2026-04-19 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_analysis_analysis_name_analysis_description_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="analysis",
            unique_together=set(),
        ),
    ]
